### ISSUE TITLE
[Issue] KrampUI won't appear on the my screen 

### ISSUE THREAD

**Issue by cmdriko** [BitdancerStudios/KrampUI#13]
I might as well go 2 for 2 and say Auto Inject is broken on the latest version when I could see the UI auto inject wasn't injecting.
KrampUI not showing up: **https://streamable.com/25pb8c**

**Comment by ByfronTechnologies** [comment]
are you on the live channel ?

**Comment by ByfronTechnologies** [comment]
oh and if you dont wanna reinstall (for some reason or it doesnt work) try pressing home when you open it?

**Comment by cmdriko** [comment]
> f you dont wanna reinstall (for some reason or it doesnt work) try pressing home when you open it?
lowkey where is the "home" button 😭

**Comment by ByfronTechnologies** [comment]
> > f you dont wanna reinstall (for some reason or it doesnt work) try pressing home when you open it?
> > lowkey where is the "home" button 😭

home, not sure ifi yoru keyboard has it
 ![image](https://github.com/BitdancerStudios/KrampUI/assets/150259300/01234c2f-2f5e-4473-9000-2dce21f1cf17)

**Comment by cmdriko** [comment]
> > > f you dont wanna reinstall (for some reason or it doesnt work) try pressing home when you open it?
> > > lowkey where is the "home" button 😭
> 
> home, not sure ifi yoru keyboard has it, what keyboard are you using? ![image](https://private-user-images.githubusercontent.com/150259300/322660586-01234c2f-2f5e-4473-9000-2dce21f1cf17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMjY1MzgsIm5iZiI6MTcxMzIyNjIzOCwicGF0aCI6Ii8xNTAyNTkzMDAvMzIyNjYwNTg2LTAxMjM0YzJmLTJmNWUtNDQ3My05MDAwLTJkY2UyMWYxY2YxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQwMDEwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTBkZDA4NGU5ZmZlMjU5MGE2NTNjOTFjOTI4MmFlZTljOTM1NzM0NTU1NzQ4NzNjODM3ZmMwNGRmNGRlMzNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aoSQyAOyEbSdysqTXvwG0X5o1ox_-BIpzii9grzgf_o)

A keyboard that doesn't have the home button 💀

**Comment by cmdriko** [comment]
> are you on the live channel for roblox, and try reinstalling krampUI,

yep I checked and did all that and it still not there lmao

**Comment by ByfronTechnologies** [comment]
> > > > f you dont wanna reinstall (for some reason or it doesnt work) try pressing home when you open it?
> > > > lowkey where is the "home" button 😭
> > 
> > 
> > home, not sure ifi yoru keyboard has it, what keyboard are you using? ![image](https://private-user-images.githubusercontent.com/150259300/322660586-01234c2f-2f5e-4473-9000-2dce21f1cf17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMjY1MzgsIm5iZiI6MTcxMzIyNjIzOCwicGF0aCI6Ii8xNTAyNTkzMDAvMzIyNjYwNTg2LTAxMjM0YzJmLTJmNWUtNDQ3My05MDAwLTJkY2UyMWYxY2YxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQwMDEwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTBkZDA4NGU5ZmZlMjU5MGE2NTNjOTFjOTI4MmFlZTljOTM1NzM0NTU1NzQ4NzNjODM3ZmMwNGRmNGRlMzNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aoSQyAOyEbSdysqTXvwG0X5o1ox_-BIpzii9grzgf_o)
> 
> A keyboard that doesn't have the home button 💀

im guessing you dont have the home button?

**Comment by ByfronTechnologies** [comment]
have you tried to go into task manager and see if theres anything that is krampui in background processes and just like closing it and then reopening krampui?

**Comment by cmdriko** [comment]
> have you tried to go into task manager and see if theres anything that is krampui in background processes and just like closing it and then reopening krampui?

It doesn't show in task manager lmao (unless I'm blind or something)

**Comment by ByfronTechnologies** [comment]
> > have you tried to go into task manager and see if theres anything that is krampui in background processes and just like closing it and then reopening krampui?
> 
> It doesn't show in task manager lmao (unless I'm blind or something)

then i have LITERALLY no idea.. have you tried restarting your computer?

**Comment by YSoSerious3Ruh** [comment]
Im having the same problem any fix

**Comment by Pixeluted** [comment]
Fixed in newest release
