### ISSUE TITLE
scripts not showing and getting error when injecting 

### ISSUE THREAD

**Issue by FANTA542** [BitdancerStudios/KrampUI#5]
when i load up the ui it doesnt show my scripts its just blank and i cant put any new scripts  in it 

i keep receiving a error message about the 1.1.1.1 vpn and i have it on and its running but im still getting it will provide pictures
![Screenshot 2024-04-13 082626](https://github.com/BitdancerStudios/KrampUI/assets/84357122/1bfb8be3-3652-4ab0-ae96-da12d95dafe9) you have to repaste it i dont know why it keeps  going as a link 
![image](https://github.com/BitdancerStudios/KrampUI/assets/84357122/4782a472-3cd1-4ac2-98ae-c2587f7fc463)
please fix

**Comment by FANTA542** [comment]
i cant type in the script box or anything

**Comment by snipcola** [comment]
Issue should be resolved by commit bcae7c8 and in version v1.1.2.
