### ISSUE TITLE
ERROR MESSAGE GETTING IT OVER AND OVER EVEN THO I HAVE 1.1.1.1 ENABLED

### ISSUE THREAD

**Issue by FANTA542** [BitdancerStudios/KrampUI#6]
![image](https://github.com/BitdancerStudios/KrampUI/assets/84357122/5b854086-9944-48b5-a400-8f2b90e718f7)
![image](https://github.com/BitdancerStudios/KrampUI/assets/84357122/3b2514f3-abff-4ea7-a549-722e906caab4)

**Comment by ByfronTechnologies** [comment]
try reinstalling the loader from acedia.gg thhen right click on the inject button in krampui and press "select loader" then well.. select the loader

**Comment by FANTA542** [comment]
WORKED
THX
