### ISSUE TITLE
[Issue] Auto Inject ain't injecting/breaks Roblox

### ISSUE THREAD

**Issue by cmdriko** [BitdancerStudios/KrampUI#8]
Lowkey ain't compatible with Roblox account manager 
Video: https://streamable.com/dfsdu6

**Comment by ByfronTechnologies** [comment]
maybe its down, or  try injecting yourself when the bloxstrap "connecting to roblox" finishes

**Comment by cmdriko** [comment]
Yeah that obv fixes the issues if you are not using Krampui maybe if they delayed the injection process by 30 seconds it would fixed the issue

**Comment by Pixeluted** [comment]
Auto injection delay is now configurable in settings, thanks for bring this up.
